### ISSUE TITLE
mod_oauth2 authentication Azure

### ISSUE THREAD

**Issue by jrohlicek-aplis** [zmartzone/mod_oauth2#4]
Hello, I have compiled and installed mod_oauth2 to apache 2.4 webserver, setup virtual host
`<Location` /oauth>
    OAuth2TokenVerify introspect https://login.windows.net/7cbec1d6-d5b2-42cf-abd1-1842a4a2d6cf/oauth2/token introspect.ssl_verify=false&introspect.auth=client_secret_basic&client_id=4951650e-34cc-407d-8423-fc3749603fc0&client_secret=*********
   AuthType oauth2
   AuthName "OAUTH2 -> AZURE_AD"
   Require valid-user
   ProxyPass !
</Location>`

but the client browser is not redirected to Azure authentication nor is authenticated, get 401 Unauthorized
What I do wrong?
Is anywhere some sample configuration to follow?
Thanks.

**Comment by zandbelt** [comment]
It seems you're looking for an OpenID Connect RP implementation rather than an OAuth 2.0 Resource Server. The former is done with: https://github.com/zmartzone/mod_auth_openidc

About the latter: mod_oauth2 does not apply in a browser-based redirect flow, it expects an `access_token` in the request, presented by a non-browser client.
